spring:
  # OAuth2 social login 설정.
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 796025688077-hqc2e6abkjbg7bj08nhrbqbvu3k21mmb.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: email
          naver:
            client-id: yJzsI9ggxgPZoCCR9S0l
            client-secret: DNZZ4x_23p
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization-grant-type: authorization_code
            scope:
              - email
            client-name: Naver
          kakao:
            client-id: 3b07a5202438033c59f75ee9f58f8674
            client-secret: FvbJSCpBsGqEH47mxzcxCGjKkkBmnRis
            scope:
              - account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-authentication-method: client_secret_post

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # key-value store인  redis 설정 (임시)
  data:
    redis:
      host: j9b308.p.ssafy.io
      port: 1234

# main DB 인 MariaDB 설정 (임시)
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://j9b308.p.ssafy.io:5555/masoori?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ssafy_b308
    password: ssafy_b308_1

# H2 설정 (로컬 테스트용)
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/dataJpa
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 10
#        use_sql_comments: true
#        show_sql: true
        format_sql: true
# log 레벨 설정
logging:
  level:
    org:
      hibernate: debug
# OAuth2 redirect url 설정
app:
  oauth2:
    authorizedRedirectUris: https://j9b308.p.ssafy.io/oauth/redirect

# jwt secret key 설정
jwt:
  key: YourewaitingforatrainAtrainthatwilltakeyoufarawayYouknowwhereyouhope

# ssl 설정
#server:
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password:1q2w3e4r
#    key-store-type: PKCS12

